### ISSUE TITLE
Kill old or hung omni processes

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-ch#253] opened 2015-05-20 05:35 UTC
When omni tries to talk to an AM that is down, the omni process hangs  (due to limitations in python 2.6 SSL) rather than timeout. As a result, these processes accumulate and can eventually lead to the CHAPI services being non-responsive. We're not sure exactly what scare resource is being exhausted.

We plan to write a cron job which will look for omni processes that have been running for longer than N minutes (a parameter, suggested default=60) and kill them. Such a process should kill all these hung processes without affecting any 'live' processing.

 _Imported from trac ticket [#253](http://trac.gpolab.bbn.com/chapi/ticket/253),  created by mbrinn on 03-11-2014 at 16:03, last modified: 05-23-2014 at 13:34_

**Comment by ahelsing** [comment] 2015-05-20 05:35
_nasir attached [dossl.patch](http://trac.gpolab.bbn.com/chapi/attachment/ticket/253/dossl.patch) on 03-13-2014 at 15:32_

**Comment by ahelsing** [comment] 2015-05-20 05:35
Using Omni 2.4.1

I had noticed this a couple of times at the GeniDesktop that uses omni as a library in the backend now since the past few weeks. After debugging this issue yesterday again when i noticed this, it had occurred when OMNI runs the GetVersion  automatically (or user forced it to) for that AM using the -a param .the --"raiseonAMAPIv2Error" has no effect since no exception is raised. 

The issue is the _do_ssl routine in gcf/src/omnilib/utils/dossl.py 

The exception was an SSLError exception but had the value of "None" for both exc.errno and exc.strerror variables . There is no check for exc.message. The error message was stored in this variable. So in the exception handling for SSLError, if exc.message is searched for a string that contains "timeout out", you should be able to catch this scenario. I had tried my hand at it, but i must be missing something becasue it worked when performing the listresources operation for an AM, but then did not work for the listresources operation to fetch a manifest for the slice (was done using omni as a library).  I am attaching the patch file with the lines i added commented out. It does not serve as a solution, but may be a pointer to the way it may/could be fixed.

_Trac comment by nasir on 03-13-2014 at 15:33_

**Comment by ahelsing** [comment] 2015-05-20 05:36
I had saved this from when i saw the issue too. As you see its hung right after trying to perform a getversion.

/opt/gcf/src/omni.py -c ~/hussamn-portal-omni.cfg listresources --slicecred=/apacheuser/slicecredentials/ch_geni_net-UKGENI-gec17dem-gec19a-slicecredential.xml urn:publicid:IDN+ch.geni.net:UKGENI+slice+gec19a -a https://geni.renci.org:11443/orca/xmlrpc --debug
17:27:36 INFO     omni: Loading agg_nick_cache file '/root/.gcf/agg_nick_cache'
17:27:36 INFO     omni: Loading config file /root/hussamn-portal-omni.cfg
17:27:36 INFO     omni: Using control framework portal
17:27:36 DEBUG    omni: Using framework type pgch
17:27:36 DEBUG    omni.protogeni: Configured with key file /root/hussamn-portal.pem
17:27:36 DEBUG    omni.protogeni: Using clearinghouse https://ch.geni.net:8443/
17:27:36 DEBUG    omni.protogeni: Using slice authority https://ch.geni.net:8443/
17:27:36 DEBUG    omni: User Cert File: /root/hussamn-portal.pem
17:27:36 INFO     omni: Python: CPython 2.7.3
OS: Linux-3.2.0-60-generic-pae-i686-with-Ubuntu-12.04-precise
Omni: GENI Omni Command Line Aggregate Manager Tool Version 2.4.1
Copyright (c) 2013 Raytheon BBN Technologies
17:27:36 DEBUG    omni: Checking cache for https://geni.renci.org:11443/orca/xmlrpc
17:27:36 DEBUG    omni: Actually calling GetVersion
17:27:36 DEBUG    omni:  ... cachedVersion was None
17:27:36 DEBUG    omni:  ... Trying to get cache using v2


_Trac comment by nasir on 03-13-2014 at 15:34_

**Comment by tcmitchell** [comment] 2015-05-20 05:36
This is not a chapi issue. It is a duplicate of (and fixed by) http://trac.gpolab.bbn.com/proto-ch/ticket/863.

_Trac comment by tmitchel (github user: tcmitchell) on 05-23-2014 at 13:34_

**Closed by tcmitchell** 2015-05-20 05:36 UTC
Labels: duplicate, general, task
