### ISSUE TITLE
authorization error on PGCH RenewSlice calling update_slice

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#271] opened 2015-05-20 05:43 UTC
In the last couple days we see some people using the old PGCH interface to renew a slice and getting authorization errors.
I have not managed to reproduce this error.

Sample logs:
```
> 04/15/2014 10:29:39:INFO    :amsoil:[pgchv1] Called: <RenewSlice>
> 04/15/2014 10:29:39:INFO    :chapi:PGCH: AGIL@clemson.edu: Invoked RenewSlice Options {} Arguments {'credential': '<?xml version="1.0"?>\n<signed-credential xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.planet-lab.org/resources/sfa/credential.xsd" xsi:schemaL...
> 04/15/2014 10:29:39:INFO    :chapi:SA: AGIL@clemson.edu: Invoked update_slice Options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} Arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece-440-640-s14+slice+TeamProject-AHZ'}
> 04/15/2014 10:29:39:ERROR   :amsoil:[sav1] [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method update_slice with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece-440-640-s14+slice+TeamProject-AHZ'} queries ['ME.MAY_UPDATE_SLICE_urn_publicid_IDN_ch_geni_net_ece_440_640_s14_slice_TeamProject_AHZ<-CALLER', 'ME.MAY_UPDATE_SLICE<-CALLER'])
> 04/15/2014 10:29:39:INFO    :chapi:SA: AGIL@clemson.edu: Result from update_slice: {'output': "[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method update_slice with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:e...
> 04/15/2014 10:29:39:INFO    :chapi:PGCH: AGIL@clemson.edu: Result from RenewSlice: {'output': "[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method update_slice with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece...
```

The user making the call (AGIL@clemson) is the LEAD of the slice they are trying to renew. Note their mixed case EPPN (and email) in case that is relevant.

By my read, this should be allowed. I cannot see yet why it is not being allowed.

That is, assuming that the method assert_slice_role is being called with a label of SLICE_URN (not lowercase slice_urn), then it looks like you should get the assertion ME.IS_LEAD_<slice> <-CALLER
where the new policy says:
      "assertions" : [
        "ME.IS_$ROLE_$SLICE<-CALLER"
    ],
      "policies" : [
         "ME.MAY_$METHOD<-ME.IS_OPERATOR",
         "ME.MAY_$METHOD_$SLICE<-ME.IS_LEAD_$SLICE",
         "ME.MAY_$METHOD_$SLICE<-ME.IS_ADMIN_$SLICE"
      ]

 _Imported from trac ticket [#271](http://trac.gpolab.bbn.com/chapi/ticket/271),  created by ahelsing on 04-15-2014 at 14:59, last modified: 05-23-2014 at 15:12_

**Comment by ahelsing** [comment] 2015-05-20 05:43
Marshall was not able to reproduce this.

The slice was created well before the time of this error message. And currently expires in May, so it worked later.

Specifically, it failed at 10:29 but worked at 10:35

```
04/15/2014 10:29:39:INFO    :chapi:PGCH: AGIL@clemson.edu: Invoked RenewSlice Options {} Arguments {'credential': '<?xml version="1.0"?>\n<signed-credential xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.planet-lab.org/resources/sfa/credential.xsd" xsi:schemaL...
04/15/2014 10:29:39:INFO    :chapi:SA: AGIL@clemson.edu: Invoked update_slice Options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} Arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece-440-640-s14+slice+TeamProject-AHZ'}
04/15/2014 10:29:39:ERROR   :amsoil:[sav1] [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method update_slice with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece-440-640-s14+slice+TeamProject-AHZ'} queries ['ME.MAY_UPDATE_SLICE_urn_publicid_IDN_ch_geni_net_ece_440_640_s14_slice_TeamProject_AHZ<-CALLER', 'ME.MAY_UPDATE_SLICE<-CALLER'])
04/15/2014 10:29:39:INFO    :chapi:SA: AGIL@clemson.edu: Result from update_slice: {'output': "[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method update_slice with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:e...
04/15/2014 10:29:39:INFO    :chapi:PGCH: AGIL@clemson.edu: Result from RenewSlice: {'output': "[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method update_slice with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece...
```

and then

```
04/15/2014 10:29:39:INFO    :chapi:PGCH: AGIL@clemson.edu: Invoked RenewSlice Options {} Arguments {'credential': '<?xml version="1.0"?>\n<signed-credential xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.planet-lab.org/resources/sfa/credential.xsd" xsi:schemaL...
04/15/2014 10:29:39:INFO    :chapi:SA: AGIL@clemson.edu: Invoked update_slice Options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} Arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece-440-640-s14+slice+TeamProject-AHZ'}
04/15/2014 10:29:39:ERROR   :amsoil:[sav1] [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method update_slice with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece-440-640-s14+slice+TeamProject-AHZ'} queries ['ME.MAY_UPDATE_SLICE_urn_publicid_IDN_ch_geni_net_ece_440_640_s14_slice_TeamProject_AHZ<-CALLER', 'ME.MAY_UPDATE_SLICE<-CALLER'])
04/15/2014 10:29:39:INFO    :chapi:SA: AGIL@clemson.edu: Result from update_slice: {'output': "[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method update_slice with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:e...
04/15/2014 10:29:39:INFO    :chapi:PGCH: AGIL@clemson.edu: Result from RenewSlice: {'output': "[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method update_slice with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece...
...
04/15/2014 10:35:52:INFO    :chapi:PGCH: AGIL@clemson.edu: Result from RenewSlice: {'output': '', 'code': 0, 'value': '<?xml version="1.0"?>\n<signed-credential xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.planet-lab.org/resources/sfa/credential.xsd" xsi:sch...
```


_Trac comment by ahelsing on 04-17-2014 at 15:57_

**Comment by ahelsing** [comment] 2015-05-20 05:43
oops, the second snippet should read:
```
04/15/2014 10:35:51:INFO    :amsoil:[pgchv1] Called: <RenewSlice>
04/15/2014 10:35:51:INFO    :chapi:PGCH: AGIL@clemson.edu: Invoked RenewSlice Options {} Arguments {'credential': '<?xml version="1.0"?>\n<signed-credential xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.planet-lab.org/resources/sfa/credential.xsd" xsi:schemaL...
04/15/2014 10:35:51:INFO    :chapi:SA: AGIL@clemson.edu: Invoked update_slice Options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} Arguments {'slice_urn': 'urn:publicid:IDN+ch.geni.net:ece-440-640-s14+slice+TeamProject-AHZ'}
04/15/2014 10:35:51:INFO    :chapi:LOG: AGIL@clemson.edu: Invoked log_event Options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} Arguments {'attributes': {'PROJECT': '32e5cf72-d549-41a2-bef0-d4f8f63b0924', 'SLICE': '7367af07-5773-4a79-91ff-822f4b66b520'}, 'message': 'Renewed slice TeamProject-AH...
04/15/2014 10:35:51:ERROR   :amsoil:[logv1] [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method log_event with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'attributes': {'PROJECT': '32e5cf72-d549-41a2-bef0-d4f8f63b0924', 'SLICE': '7367af07-5773-4a79-91ff-822f4b66b520'}, 'message': 'Renewed slice TeamProject-AHZ until 2014-04-18T23:59:59'} queries [u'ME.MAY_LOG_EVENT_urn_publicid_IDN_ch_geni_net_project_ece_440_640_s14<-CALLER', 'ME.MAY_LOG_EVENT<-CALLER'])
04/15/2014 10:35:51:INFO    :chapi:LOG: AGIL@clemson.edu: Result from log_event: {'output': "[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method log_event with options {'fields': {'SLICE_EXPIRATION': '2014-04-18T23:59:59Z'}} arguments {'attributes': {'PROJECT': '32e5cf72-d549-41a2-bef0...
04/15/2014 10:35:51:INFO    :chapi:SA: AGIL@clemson.edu: Result from update_slice: {'output': _, 'code': 0, 'value': True}
...
04/15/2014 10:35:52:INFO    :chapi:PGCH: AGIL@clemson.edu: Result from RenewSlice: {'output': _, 'code': 0, 'value': '<?xml version="1.0"?>\n<signed-credential xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.planet-lab.org/resources/sfa/credential.xsd" xsi:sch...
```


_Trac comment by ahelsing on 04-17-2014 at 15:59_

**Comment by tcmitchell** [comment] 2015-05-20 05:43
This hasn't happened since 4/25. In that time there have been over 80 successful RenewSlice calls via PGCH.

Closing because we were unable to reproduce the problem and haven't seen it in a month.

_Trac comment by tmitchel (github user: tcmitchell) on 05-23-2014 at 15:12_

**Closed by tcmitchell** 2015-05-20 05:44 UTC
Labels: abac, worksforme
