### ISSUE TITLE
Flack fails to initialize user

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#34] opened 2015-05-20 04:06 UTC
When Flack is launched via a portal backed by chapi the user is not logged in. The initialize user task in Flack has the error "tlsError: Certificate is not trusted."

 _Imported from trac ticket [#34](http://trac.gpolab.bbn.com/chapi/ticket/34),  created by tmitchel on 11-12-2013 at 15:55, last modified: 11-18-2013 at 18:17_

**Comment by MarshallBrinn** [comment] 2015-05-20 04:06
This problem has been tied back to a requirement to install the ca-gpolab.crt into the service registry. This is captured in proto-ch ticket #884 and this one should be closed as a duplicate of that one.

We've tested that flack works when this cert is installed in the service registry.



_Trac comment by mbrinn (github user: MarshallBrinn) on 11-13-2013 at 11:42_

**Comment by tcmitchell** [comment] 2015-05-20 04:06
In order for Flack to speak to the portal, we need to pass Flack the cert that signed the apache certs. This is located in `/etc/ssl/certs/ca-gpolab.cert`. A change should be made to the install_db script to insert this cert into the service_registry using a SQL expression like:
```
insert into service_registry (service_url, service_type, service_cert) values (, 7, '/etc/ssl/certs/ca-gpolab.crt');
```

The fix needs to go in install_db. 

_Trac comment by tmitchel (github user: tcmitchell) on 11-13-2013 at 11:47_

**Comment by ahelsing** [comment] 2015-05-20 04:06
Reminder: the location of the signing cert is different for nye than for the sandboxes, so you don't want to hardcode it as ca-gpolab.

Puppet knows the location of the correct signer for each portal/CH, so if you'd like, i can have puppet put a file in /etc/geni-chapi/ containing this insert statement with the right cert for each portal/CH, and then the installer can just execute that file.  Up to y'all.

_Trac comment by chaos on 11-13-2013 at 12:01_

**Comment by ahelsing** [comment] 2015-05-20 04:06
Per discussion with Tom, i went ahead and had apache create this file in /etc/geni-chapi.  Here's how it looks on tau-ceti:
```
$ cat /etc/geni-chapi/update_service_registry.01.sql 
-- --- Service registry insert for CH apache signing cert
--
-- DO NOT EDIT except via CVS (cvs.gpolab.bbn.com:/srv/cvs)
-- 
-- See /var/lib/puppet/vtf/apache_update_service_registry.01.sql
-- for a copy of this file containing the RCS info

insert into service_registry (service_url, service_type, service_cert) values
  (, 7, '/etc/ssl/certs/ca-gpolab.crt');

```
So the install script should be able to execute that and get the correct per-CH filename.


_Trac comment by chaos on 11-18-2013 at 14:54_

**Comment by ahelsing** [comment] 2015-05-20 04:06
Tom and i found/fixed a typo in the insert.  Now the file reads:
```
$ cat /etc/geni-chapi/update_service_registry.01.sql 
-- --- Service registry insert for CH apache signing cert
--
-- DO NOT EDIT except via CVS (cvs.gpolab.bbn.com:/srv/cvs)
-- 
-- See /var/lib/puppet/vtf/apache_update_service_registry.01.sql
-- for a copy of this file containing the RCS info

insert into service_registry (service_url, service_type, service_cert) values
  ('', 7, '/etc/ssl/certs/ca-gpolab.crt');

```


_Trac comment by chaos on 11-18-2013 at 15:14_

**Comment by tcmitchell** [comment] 2015-05-20 04:06
Fix added to install_db. If the file exists, execute it in psql.

_Trac comment by tmitchel (github user: tcmitchell) on 11-18-2013 at 18:17_

**Closed** 2015-05-20 04:07 UTC
Labels: installer, task
