### ISSUE TITLE
should you be allowed to expire a project with active slices?

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#295] opened 2015-05-20 05:53 UTC
Should chapi block you from expiring a project that has active slices (or insist you cannot expire it before the minimum slice expiration).

 _Imported from trac ticket [#295](http://trac.gpolab.bbn.com/chapi/ticket/295),  created by ahelsing on 05-21-2014 at 11:08, last modified: 07-11-2014 at 11:17_

**Comment by tcmitchell** [comment] 2015-05-20 05:53
Duplicate of issue #125.

_Trac comment by tmitchel (github user: tcmitchell) on 07-11-2014 at 11:17_

**Closed** 2015-05-20 05:53 UTC
Labels: duplicate, sa, task
