### ISSUE TITLE
Honor a CRL if present

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#261] opened 2015-05-20 05:38 UTC
Configure apache to honor a CRL, if we generate one

 _Imported from trac ticket [#261](http://trac.gpolab.bbn.com/chapi/ticket/261),  created by ahelsing on 04-02-2014 at 17:04, last modified: 08-07-2014 at 13:12_

**Comment by MarshallBrinn** [comment] 2015-05-20 05:39
Closing as a duplicate of #171 (that is, the fix for #171 handles this  as well). - Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-07-2014 at 13:12_

**Closed by MarshallBrinn** 2015-05-20 05:39 UTC
Labels: duplicate, general, task
