### ISSUE TITLE
Invalid timestamp  for project expiration not detected, throws ugly error

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#291] opened 2015-05-20 05:52 UTC
Invalid timestamp not detected, throws ugly error:

```
05/13/2014 07:46:54:ERROR   :amsoil:[sav1] [SERVER] SERVER_ERROR ((DataError) invalid input syntax for type timestamp: "2015-02-01T00:00:00Z 23:59:59"
LINE 1: ...roject SET project_purpose=E'Testing', expiration=E'2015-02-...
                                                             ^
 'UPDATE pa_project SET project_purpose=%(project_purpose)s, expiration=%(expiration)s WHERE pa_project.project_name = %(project_name_1)s' {'project_name_1': 'max_mystery_project', 'project_purpose': 'Testing', 'expiration': '2015-02-01T00:00:00Z 23:59:59'})
05/13/2014 07:46:54:ERROR   :amsoil:[sav1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/SliceAuthority.py", line 348, in update_project
    mc._session)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/sarm/SAv1PersistentImplementation.py", line 819, in update_project
    q = q.update(updates)

  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2690, in update
    update_op.exec_()
```

 _Imported from trac ticket [#291](http://trac.gpolab.bbn.com/chapi/ticket/291),  created by ahelsing on 05-14-2014 at 15:25, last modified: 05-15-2014 at 10:17_

**Comment by MarshallBrinn** [comment] 2015-05-20 05:52
Aaron and I spoke about this. The issue is that the python date parser code (dateutil.parser.parse) accepts date time strings that postgresql does not. Specifically, it seems to accept (and ignore) some trailing strings.

A few things we could do:

1- Try to catch the error from the database and create a better error message. This is hard since the error returned is not obvious to parse in general.
2- Try to change the date time in argument check (parse and then unparse the string and replace it in your request). I think this is possible but not necessarily what you want: you might wind up inserting a date you didn't intend.
3- See if SQLAlchemy has a date formatter that can tell if the database would accept the string (without actually accepting it)
4- Replace dateutil.parser.parse with code that handles exactly what postgresql handles.

We agreed that #1 and #2 aren't good solutions. 

Given that we do catch the error and return an ugly but comprehensible error, we agreed to spend a little time pursuing #3 and #4 and then either fix accordingly or close as 'wont fix'



_Trac comment by mbrinn (github user: MarshallBrinn) on 05-15-2014 at 08:49_

**Comment by MarshallBrinn** [comment] 2015-05-20 05:52
Ah, I see that this is a problem for update_project but not update_slice. Update slice takes the date string and uses a formatted version of it for insertion; update_project does not. I'll update update_project to behave like update_slice and see how it goes.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-15-2014 at 09:20_

**Comment by MarshallBrinn** [comment] 2015-05-20 05:52
I put in code in SAv1Implementation to replace the string value for the expiration with the data time object as parsed. update_slice already does this but update_project did not. Tested and ready to go.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-15-2014 at 10:17_

**Closed by MarshallBrinn** 2015-05-20 05:52 UTC
Labels: sa, task
