### ISSUE TITLE
log service guards failing from portal

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#191] opened 2015-05-20 05:08 UTC
Log service calls from the portal fail when the caller is $user and not the Portal. This appears to be due to a mismatch of attribute names and values.

As needed, fix this here or in proto-ch ticket #568

 _Imported from trac ticket [#191](http://trac.gpolab.bbn.com/chapi/ticket/191),  created by ahelsing on 12-16-2013 at 16:46, last modified: 12-20-2013 at 12:33_

**Comment by ahelsing** [comment] 2015-05-20 05:08
I noticed that in numerous places, the portal was using its own certificate to invoke log service functions. That seemed wrong, so I changed Portal::getInstance() to $user. For example, in portal/www/portal/slice.php around line 506.

Then when I load the slice page, I get:
```
12/16/2013 15:25:27:INFO    :chapi:LOG: ahelsing@geni.net: Invoked get_log_entries_for_context Options {} Arguments {'context_type': 2, 'context_id': 'f7ad623d-7053-4a8e-a314-8b103cabf21c', 'num_hours': 24}
12/16/2013 15:25:27:ERROR   :amsoil:[logv1] [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method get_log_entries_for_context with options {} arguments {'context_type': 2, 'context_id': 'f7ad623d-7053-4a8e-a314-8b103cabf21c', 'num_hours': 24} query ME.MAY_GET_LOG_ENTRIES_FOR_CONTEXT<-CALLER)
```

Note that the value of context_type is an int, and I think the guard expects a string.

Similarly, I changed renewsliver.php around line 207 to use $user. I also changed the userid argument from $slice['owner_id'] - which I think was always claiming that the slice owner took the action - to use $user->account_id.

[test on illyrica, I changed line 200 to do if (True || ..... ](To)

Then on a slice I own I hit Renew on one of the aggregates in the aggregates list.

I get this error:
```
12/16/2013 15:29:12:INFO    :chapi:LOG: ahelsing@geni.net: Invoked log_event Options {} Arguments {'attributes': {'aggregate': 'https://uh-hn.exogeni.net:11443/orca/xmlrpc', 'slice': 'urn:publicid:IDN+ch-ah.gpolab.bbn.com:ahscaletest+slice+180test4'}, 'message': 'RenewSliver at https://uh-hn.exogeni.net:1144...
12/16/2013 15:29:12:ERROR   :amsoil:[logv1] [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method log_event with options {} arguments {'attributes': {'aggregate': 'https://uh-hn.exogeni.net:11443/orca/xmlrpc', 'slice': 'urn:publicid:IDN+ch-ah.gpolab.bbn.com:ahscaletest+slice+180test4'}, 'message': 'RenewSliver at https://uh-hn.exogeni.net:11443/orca/xmlrpc on urn:publicid:IDN+ch-ah.gpolab.bbn.com:ahscaletest+slice+180test4', 'user_id': 'a34a690d-268e-4c28-888a-18e3aa995658'} query ME.MAY_LOG_EVENT<-CALLER)
```

Note that the user_id above is my user_id.
Note that the 'slice' attribute is lowercase, and the value is a URN. Both of those seem wrong.

All of this works fine currently because the portal is always using its own cert when calling the log service.


_Trac comment by ahelsing on 12-16-2013 at 16:47_

**Comment by MarshallBrinn** [comment] 2015-05-20 05:08
I fixed this specific problem. There were some mistakes/typos in the ABAC guards on get_log_entries_by_author and get_log_entries_for_context. ONce these were fixed, all works well.

There is still an open issue (captured in proto-ch #568) that we use Portal::getInstance() instead of $user on many of our log_event calls. The issue is complicated: what rights shoudd you have to write a log entry on a project to which you don't belong? I am closing this one but keeping #568 open.



_Trac comment by mbrinn (github user: MarshallBrinn) on 12-20-2013 at 12:33_

**Closed** 2015-05-20 05:08 UTC
Labels: abac, task
