### ISSUE TITLE
join a project results in an error

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#43] opened 2015-05-20 04:10 UTC
[SERVER] SERVER_ERROR ('list' object has no attribute 'has_key')

 _Imported from trac ticket [#43](http://trac.gpolab.bbn.com/chapi/ticket/43),  created by phelinek on 11-14-2013 at 14:10, last modified: 11-19-2013 at 11:58_

**Comment by tcmitchell** [comment] 2015-05-20 04:10
Duplicate of issue #42.

_Trac comment by tmitchel (github user: tcmitchell) on 11-15-2013 at 07:58_

**Closed by tcmitchell** 2015-05-20 04:10 UTC
Labels: duplicate, general, task
